---
title: "Homework 4 Problem 1"
author: "Huijuan Zhang"
date: "10/25/2017"
output: html_document
---

1. Load and tidy the pups data.

```{r}
library(tidyverse)
library(janitor)

pups_data = read_csv("./FAS_pups.csv", col_types = "ciiiii") %>%
  clean_names() %>%
  gather('pd_ears', 'pd_eyes', 'pd_pivot', 'pd_walk', key = "pd_outcome", value = "pd_days") %>% 
  filter(!is.na(pd_days))
```

2.Create a `violin` plot showing the distribution of post-natal days for each developmental landmark.

```{r setup_plot}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .7,
  out.width = "80%"
)
```


```{r plot}
library(ggthemes)

ggplot(pups_data, aes(x = pd_outcome, y = pd_days)) + 
  geom_violin(aes(fill = pd_outcome), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 2) +
  labs(
    title = "Distribution of post-natal days for Developmental landmarks",
    x = "Developmental landmark",
    y = "Post-natal days"
  ) + 
  theme(legend.position = "bottom")
```

* The outcome __eyes__ have the longest post-natal days whereas __ears__ have the shortest post-natal days. The second longest is __walk__ and third is __pivot__.